### ISSUE TITLE
First screen at launch

### ISSUE THREAD

**Issue by ximenabb** [digidem/CoMapeo-mobile#100]
## First screen at launch
- User launches CoMapeo for the first time
- User sees the permissions prompt for the devices Camera and Location
- User is invited to Get Started

![Image](https://github.com/digidem/CoMapeo-mobile/assets/67773827/d9fa142b-0aae-449d-99ed-761f1f8a3837)

![Image](https://github.com/digidem/CoMapeo-mobile/assets/67773827/a68e413a-c4fe-46e2-bcb8-6d58f73a190d)

## Todo

- [ ] Display onboarding screen with logo
- [ ] Display permissions request for Camera
- [ ] Display permissions request for Location
- [ ] Create button `Get Started` button

## Design
*** Updated design: https://digidem.slack.com/archives/D025UPW0TUG/p1697140727438439 
***old design: https://www.figma.com/file/uzynHXR0xgJu19lsCoJyXN/%F0%9F%90%9A-Shell-App?type=design&node-id=1069-4606&mode=design&t=8p1fA5Pu7n24D7E5-0

## Copydeck
https://docs.google.com/spreadsheets/d/18x135fNGqwryXcBoJGvtNSJJMHuPB48Vp0o1l16UyzY/edit?usp=sharing
