### ISSUE TITLE
Implement bug tracking software

### ISSUE THREAD

**Issue by ErikSin** [digidem/comapeo-mobile#224]
**This work should be done after #225 as there is a sentry sdk for expo managed projects**

Integrate Sentry for bug tracking

## To do:
- [x] Install Sentry SDK
- [x] Initialize DSN with public key **@ErikSin will provide once we are approved for a non profit account **
- [x] Add Sentry Expo Plugin
- [x] Add auth token as a secret key **@ErikSin will provide once we are approved for a non profit account**
- [x] Catch and log and uncaught exceptions

### Configuration
- debug mode should be turned on in development and preview builds, not production builds.
