### ISSUE TITLE
Project Invitation Declined

### ISSUE THREAD

**Issue by ximenabb** [digidem/comapeo-mobile#233]
## Invitation Declined
- Project Coordinator sends a project invite to a user/device
- As screen shows "Waiting for Device to Accept Invite", invitee declines in the invitation via https://github.com/digidem/mapeo-mobile/issues/1130
- Project Coordinator sees screen of invite declined

<img width="356" alt="Screen Shot 2024-04-06 at 12 31 57 PM" src="https://github.com/digidem/CoMapeo-mobile/assets/78557542/93629121-8f52-42bc-b130-2f0c80ec50c2">

## Todo
- [ ] Display screen as designed
- [ ] Display *Invitation Declined*
- [ ] Display *This device has declined your invitation. They have not joined the project.*
- [ ] Display *Device Name* that declined
- [ ] Create `Close` button

## Design
https://www.figma.com/file/uzynHXR0xgJu19lsCoJyXN/%F0%9F%90%9A-Shell-App?type=design&node-id=1075-5095&mode=design
