### ISSUE TITLE
Project Invitation / Unable to cancel

### ISSUE THREAD

**Issue by ximenabb** [digidem/comapeo-mobile#234]
## Unable to cancel
- Project Coordinator sends a project invite to a user/device
- As screen shows "Waiting for Device to Accept Invite" and Project Coordinator clicks on Cancel Invite https://github.com/digidem/mapeo-mobile/issues/1124, invitee accepts the invitation
- Project Coordinator sees screen they no longer can cancel the invite

<img width="348" alt="Screen Shot 2024-04-06 at 12 42 21 PM" src="https://github.com/digidem/CoMapeo-mobile/assets/78557542/6338940f-c5bb-43b9-8faa-79e7f880947a">

## Todo
- [ ] Display screen as designed
- [ ] Display *Unable to Cancel Invitation*
- [ ] Display *Device has joined Project Catapult.*
- [ ] Display *Device Name* and *Role* that accepted invitation
- [ ] Create `Close` button

## Design
https://www.figma.com/file/uzynHXR0xgJu19lsCoJyXN/%F0%9F%90%9A-Shell-App?type=design&node-id=1075-5095&mode=design
