### ISSUE TITLE
Project Settings/ Your Team/ deviced disconnected

### ISSUE THREAD

**Issue by ximenabb** [digidem/comapeo-mobile#235]
When inviting other devices to a project, user can see a list of available devices on the network. When one of those available devices disconnect from the network, we show that device as disconnected. 

We do not want the device that disconnected to be removed from the list, nor do we want the order of the list to change (new devices should added to the bottom). 

This screen can be found [here](https://github.com/digidem/comapeo-mobile/blob/main/src/frontend/screens/Settings/ProjectSettings/YourTeam/SelectDevice.tsx)

## User flow of deviced disconnected
- Project Coordinator was on Project Settings and clicked on **Your team**
- Project Coordinator is on a project and can see the project and available devices
- 1 or more devices disconnect : Use case -  bad internet connection.
- Project Coordinator and others see the disconnect devices on the **Your Team** screen and **Select Device to Invite** screen

## Todo
- [x] Add the orange icon and display *Disconnected* under the disconnected devices
- [x] If the user is disconnected, the `onPress` should be disabled.
- [x] Icon should be removed and button re-enabled if the user re-connects

<img width="697" alt="Screen Shot 2024-04-06 at 12 55 18 PM" src="https://github.com/digidem/CoMapeo-mobile/assets/78557542/7a326af8-4188-486e-82a7-1823db6fa87c">

<img width="171" alt="Screen Shot 2024-04-06 at 12 53 51 PM" src="https://github.com/digidem/CoMapeo-mobile/assets/78557542/d15eb453-9558-4b40-ab38-564be00c920b">
<img width="173" alt="Screen Shot 2024-04-06 at 12 54 07 PM" src="https://github.com/digidem/CoMapeo-mobile/assets/78557542/909e8c08-0fad-47ab-9056-c89f7e2ad7ca">

## Design
https://www.figma.com/file/uzynHXR0xgJu19lsCoJyXN/%F0%9F%90%9A-Shell-App?type=design&node-id=1075-5095&mode=design&t=1zbIlqd9eRkTVFTz-0
