### ISSUE TITLE
GPS/Location is on

### ISSUE THREAD

**Issue by ximenabb** [digidem/comapeo-mobile#237]
## GPS/Location is on
- User is on CoMapeo and their GPS is enabled
- User can use the Tracks feature 

<img width="413" alt="Screen Shot 2024-04-08 at 1 58 28 PM" src="https://github.com/digidem/CoMapeo-mobile/assets/78557542/88340ef6-90ef-4083-8154-27fedd3c2224">

## Todo

- [x] Use same designs as in the GPS Off state https://github.com/digidem/CoMapeo-mobile/issues/236
- [x] GPS pill displays being enabled
- [x] When tracks button clicked - display bottom sheet modal
- [x] In modal, create `Start Tracks` button 

## Design
https://www.figma.com/file/1Knqv1NrijUuqMo1pvYyF7/Tracks-and-Audio-(Share)?type=design&node-id=3-1220&mode=design&t=l4GvAUToI92yOh3D-0
