### ISSUE TITLE
Recording Tracks

### ISSUE THREAD

**Issue by ximenabb** [digidem/comapeo-mobile#238]
## Recording Tracks
- User taps on Start Tracks and tracks beings recording
- An additional line appears with a runtime of Tracks recording
- `Start Tracks` button  turns into a `Stop Tracks` button
- Distance will be recorded in meters, kilometers
- Time will be recorded in seconds, minutes, hours
- Tracks can be recording in the background as user navigates other sections of CoMapeo
- Observations can be created as Tracks are being recorded

## Todo

<img width="696" alt="Screen Shot 2024-04-08 at 2 24 03 PM" src="https://github.com/digidem/CoMapeo-mobile/assets/78557542/85ae0367-b86e-42b3-8000-32e2bea7df3e">

## Starting a track

- [x] Turn blue`Start Tracks` button into red `Stop Tracks` button
- [x] Display line under  `Stop Tracks` button  with a runtime of Tracks recording - *You’ve been recording for 00:00:00*
- [x] Display runtime on the Tracks button 
- [x] Display length (in meters) and runtime on the map, use design as seen on Figma
- [x] Display all runtimes as long as the track is recording

## Recording a track

<img width="873" alt="Screen Shot 2024-04-08 at 2 40 02 PM" src="https://github.com/digidem/CoMapeo-mobile/assets/78557542/45a8fcb9-35fd-4004-9ffd-4edd5fcac71d">

- [x] Keep tracks recording in the background
- [x] Display the tracks path on the map as a line

## Design
https://www.figma.com/file/1Knqv1NrijUuqMo1pvYyF7/Tracks-and-Audio-(Share)?type=design&node-id=72-1761&mode=design&t=uliZJlzlAUbMNi91-0
