### ISSUE TITLE
Use map serving functionality of mapeo core

### ISSUE THREAD

**Issue by achou11** [digidem/comapeo-mobile#243]
## Description

As part of the work for https://github.com/digidem/mapeo-core-next/issues/437, we made online and offline (both custom + fallback) map serving the responsibility of the http server that's used in tandem with mapeo core. This feature has not yet been integrated into the app yet, but doing so would allow the frontend to avoid any logic around map style url resolving based on network states.

## Tasks

- backend
  - [x] set up fastify plugins for serving maps
  - [x] add default offline map (from https://github.com/digidem/mapeo-offline-map?) as an asset that's included in the app

- frontend
  - [x] update the style url used any MapView instances to use the url returned by `MapManager.getMapStyleJsonUrl()`
