### ISSUE TITLE
Invite canceled

### ISSUE THREAD

**Issue by ximenabb** [digidem/comapeo-mobile#287]
## Invite to project has been canceled
- Project Coordinator sends a project invite to a user/device and screen shows "Waiting for Device to Accept Invite" https://github.com/digidem/mapeo-mobile/issues/1124
- Project Coordinator cancels the invite - 5 in this issue https://github.com/digidem/mapeo-mobile/issues/1124
- Project Participant see the cancelation of the invite

<img width="193" alt="Screen Shot 2024-04-23 at 11 00 20 AM" src="https://github.com/digidem/comapeo-mobile/assets/78557542/9ca25b71-db28-4736-a7ef-0f2bb44e66fb">

## Todo
- [ ] Update the bottom nav drawer
- [ ] Display *Invite Canceled!**
- [ ] Display **Your invitation to XX has been canceled.**
- [ ] Create `Close` button

## Design
https://www.figma.com/file/uzynHXR0xgJu19lsCoJyXN/%F0%9F%90%9A-Shell-App?type=design&node-id=1196%3A1914&mode=design&t=h4uu0UEPvqYc252k-1
