### ISSUE TITLE
New / Edit Observation - No attachments

### ISSUE THREAD

**Issue by ximenabb** [digidem/comapeo-mobile#356]
## New / Edit Observation - No attachments
Introducing the  new *Audio* feature by adding the **Microphone** icon as part of additional options to the **New / Edit Observation** screen. Therefore, this screen requires updates to be better display the additional options.

## Todo

<img width="471" alt="Screen Shot 2024-05-15 at 1 55 23 PM" src="https://github.com/digidem/comapeo-mobile/assets/78557542/d0e12c16-7e4a-4add-bab0-8b6cae8caa43">

##  Update screen 
Update the following as designed :
<img width="187" alt="Screen Shot 2024-05-15 at 2 34 58 PM" src="https://github.com/digidem/comapeo-mobile/assets/78557542/716d9494-b458-4d72-9472-1aab6c5971bf">

- [x] Update designs of **Title + Change**
- [x] Move and update the Coordinates, add the orange icon next to coordinates
- [x] Update the "what is happening here?" area
- [x] Update the bottom menu as designed
- [x] Update all the icons with a + 
- [x] Display Microphone icon as part of additional options

##  What is happening here? flow
- [x] When clicking on "what is happening here?", pull up the device keyboard
- [x] If keyboard open, if user taps anywhere else, bring back to the starting state

## Design
https://www.figma.com/design/1Knqv1NrijUuqMo1pvYyF7/Tracks-and-Audio-(Share)?node-id=529-916&t=V0vmc8SZM3TxMGuM-0
