### ISSUE TITLE
New / Edit Observation - With attachments

### ISSUE THREAD

**Issue by ximenabb** [digidem/comapeo-mobile#357]
## New / Edit Observation - With attachments
Once a user added any new media to an observation, we will now introduce a carrousel to this view so users can scroll all available media. 
The logic of saving an observation is handled by Dd.

<img width="211" alt="Screen Shot 2024-05-15 at 2 52 16 PM" src="https://github.com/digidem/comapeo-mobile/assets/78557542/604dbc45-3788-4bc1-bcc1-17e4ba195836">

## Todo
- [x] When a user attaches many audio recordings or photos, display them in a **carouse**l, on top of the menu
- [x] For audio display;
- [x] The Play icon
- [x]  Length of the recording in minutes and seconds (example 02:00)
- [x] Time of creation in seconds, minutes, hours
<img width="117" alt="Screen Shot 2024-05-15 at 2 48 34 PM" src="https://github.com/digidem/comapeo-mobile/assets/78557542/0653ceb6-94cc-4b58-8a26-434c332473c9">

## Design
https://www.figma.com/design/1Knqv1NrijUuqMo1pvYyF7/Tracks-and-Audio-(Share)?node-id=529-1183&t=V0vmc8SZM3TxMGuM-0
