### ISSUE TITLE
Saving Observation

### ISSUE THREAD

**Issue by ximenabb** [digidem/comapeo-mobile#358]
## Saving Observation
Tapping on Blue Check button saves the observation.  The user is taken to this confirmation screen.

## Todo
<img width="192" alt="Screen Shot 2024-05-15 at 2 59 53 PM" src="https://github.com/digidem/comapeo-mobile/assets/78557542/b2d6f0bb-ccd7-4807-affe-85094d6082ab">

- [ ] Display screen as designed
- [ ] Add success checkmark
- [ ] Add **Your Observation was added** text
- [ ] Display `Return to map` button, when clicked redirect to the map
- [ ] Display `View observations` button, when clicked redirect to the observations list

## Design
https://www.figma.com/design/1Knqv1NrijUuqMo1pvYyF7/Tracks-and-Audio-(Share)?node-id=529-600&t=V0vmc8SZM3TxMGuM-0
