### ISSUE TITLE
Microphone Permissions

### ISSUE THREAD

**Issue by ximenabb** [digidem/comapeo-mobile#359]
## Microphone Permissions
As we introduce audio, comapeo will ask users to give it permission to the microphone. 
Important to note - we are not creating a custom "Permission Bottom Sheet - Microphone".

## Todo

**User clicks on mic icon for first time : Request Bottom Sheet - Microphone**
<img width="468" alt="Screen Shot 2024-05-15 at 7 03 13 PM" src="https://github.com/digidem/comapeo-mobile/assets/78557542/e37a934c-688d-4427-911c-e95824a03b7a">

- [ ] Display screen as designed
- [ ] Add microphone icon with _Recording Audio with CoMapeo_ as title
- [ ] Display text _To record audio while using the app  and in the background CoMapeo needs to access your microphone._
- [ ] Display `Not now` button, when clicked redirect to to the starting state (New / Edit Obvservation)
- [ ] Display `Allow` button, when clicked open the android system permission dialog

**User wh
<img width="201" alt="Screen Shot 2024-05-15 at 7 03 31 PM" src="https://github.com/digidem/comapeo-mobile/assets/78557542/956b51a3-afb6-41ab-9168-b7b60c7978cd">
o have previously denied permission**

- [ ] Display screen like the _Request Bottom Sheet - Microphone_ screen
- [ ] Display `Not now` button, when clicked redirect to to the starting state (New / Edit Obvservation)
- [ ] Display `Go to Settings` button, when clicked open the android settings

**Tapping on either “While using the app” or “Only this time”**
- [ ] Take user to https://github.com/digidem/comapeo-mobile/issues/360

**Tapping "Don't allow"**
- [ ] First time - Take user to starting state
- [ ] Second time - take to settings

## Design
https://www.figma.com/design/1Knqv1NrijUuqMo1pvYyF7/Tracks-and-Audio-(Share)?node-id=529-812&t=V0vmc8SZM3TxMGuM-0
