### ISSUE TITLE
New audio recording

### ISSUE THREAD

**Issue by ximenabb** [digidem/comapeo-mobile#360]
## New audio recording
Tapping on either “While using the app” or “Only this time” takes the user this interface.
User can record up to 5 minutes of audio.

## Todo

**New Audio Recording - Start**
<img width="193" alt="Screen Shot 2024-05-15 at 3 53 16 PM" src="https://github.com/digidem/comapeo-mobile/assets/78557542/7d7d3f49-59df-4eb3-97d8-89f4994a1b37">
- [x] Display screen as designed
- [x] Display counter at 00:00
- [x] Display text Record up to 5 minutes
- [x] Display red circle record button, when tapped start recording as _New Audio Recording - In Progress_

**New Audio Recording - In Progress**
<img width="200" alt="Screen Shot 2024-05-15 at 3 57 17 PM" src="https://github.com/digidem/comapeo-mobile/assets/78557542/c3e36011-b1ac-4576-a300-de78ee13777d">
- [x] Display countdown of minutes left to the recording, starting at 5mins
- [x] Update the red circle record button to the recording button, as designed
- [x] To display the progress in color - the record screen “fills up” with blue, e.g. a horizontal block of blue starts at the bottom of the screen and slowly expands to fill the screen until the entire screen is blue at 5 minutes.  !!! SWM team - can you let me know if that logic makes sense or need more details? 

**New Audio Recording - 60-second Alert**
<img width="190" alt="Screen Shot 2024-05-15 at 4 07 21 PM" src="https://github.com/digidem/comapeo-mobile/assets/78557542/2e95c0b3-4389-4cbd-b0d3-3e5070f1d7be">
- [x] When Audio Recording reaches 60-seconds left, brighten the blue to Mapeo Blue

**Stop recording button**
- [x] Tapping the “Stop” button, ends the Audio Recording and  displays the Playback interface

**Playback interface**
<img width="197" alt="Screen Shot 2024-05-15 at 4 11 13 PM" src="https://github.com/digidem/comapeo-mobile/assets/78557542/ce973467-d019-46a9-b2e4-b588dc145ef4">
- [x] Tapping the “X” button, attaches the audio to Observation Draft and takes user to “Success” confirmation.
- [x] Display audio progress bar
- [x] Display _Total length_ and the length in minutes
- [x] Display Play button, to replay audio
- [x] Display Trash Can button, when clicks takes to the Delete screen

**Success Confirmation**
<img width="195" alt="Screen Shot 2024-05-15 at 4 16 04 PM" src="https://github.com/digidem/comapeo-mobile/assets/78557542/13c18214-b405-46a4-bb9d-105297ce140d">
- [x] Display screen as designed
- [x] Display Success green icon with _Success!_ text
- [x] Display `Return to editor` button, when clicked redirects to the _New / Edit Obvservation_
- [x] Display `Record Another` button, when clicked go to _New Audio Recording - Start_

## Design
https://www.figma.com/design/1Knqv1NrijUuqMo1pvYyF7/Tracks-and-Audio-(Share)?node-id=529-856&t=V0vmc8SZM3TxMGuM-0
