### ISSUE TITLE
Playback / Delete / Share

### ISSUE THREAD

**Issue by ximenabb** [digidem/comapeo-mobile#361]
## Playback / Delete / Share
User has successfully saved an audio recording on a observation. User clicks on the recording from the observation. User can play it back, delete it or share it.

## Todo
<img width="709" alt="Screen Shot 2024-05-15 at 4 25 21 PM" src="https://github.com/digidem/comapeo-mobile/assets/78557542/f9910010-c762-4114-856f-927eabbd2d47">

**Playback**
- [ ] Task is already here https://github.com/digidem/comapeo-mobile/issues/360
- [x] Only difference is, tapping the “X” button takes user to the Observation

**Delete Audio Recording**
- [x] Display bottom sheet as designed
- [x] Display red icon and _Delete?_
- [x] Display text _Your Audio Recording will be permanently deleted. This cannot be undone._ 
- [x] Display `Delete` button, when clicked redirects to the Observation
- [x] Display `Cancel` button, when clicked close the modal

**Share**
- [ ] **No** creating a custom share sheet (we need to update figma)
- [ ] When tap share, use android share sheet

## Design
https://www.figma.com/design/1Knqv1NrijUuqMo1pvYyF7/Tracks-and-Audio-(Share)?node-id=529-657&t=xhcTH3fFF4S8gJjD-0

**Comment by ximenabb** [comment]
Update :
Shared by @CDFN -
_Hi, there is problem we encountered when developing share menu. Default Android SMS app (com.google.android.apps.messaging) isn't able to handle android.intent.action.SEND_MULTIPLE intent with audio/mp4 mime type, meaning we can't share audio via SMS as in design. WhatsApp works fine though. Apparently default SMS app is only capable of doing image/* and text/* mime types :disappointed:
You'll need to make decision whether you want to use something else (different app) in place of messages or find some different solution. Let me know how we should proceed with this._


**Decision made** - share Whatsapp and More fore the MVP

**Comment by CDFN** [comment]
This issue can't be finished in full before #378 gets added, as currently there is no way to store attachment metadata (need to store creation timestamp + recording duration)
