### ISSUE TITLE
Sync update / Pre-Sync

### ISSUE THREAD

**Issue by ximenabb** [digidem/comapeo-mobile#602]
**Description**
Important to note:
- Devices found = devices who are on the same project and network and are anywhere in the app
- Syncing devices = devices who have clicked on "Start Sync" on the Sync screen and have opted-in to join the syncing party
- Before joining the sync party, user can see how many devices are found, user cannot see if/how many people have joined the sync party

Details : https://www.notion.so/digidem/QA-Sync-bug-3-devices-no-synced-progress-3de5f1760e934b12b673bb49b62572ec

Relates to https://github.com/digidem/comapeo-mobile/issues/603 https://github.com/digidem/comapeo-mobile/issues/604 https://github.com/digidem/comapeo-mobile/issues/605

**Todo**

## Screen 1 - No other device is on the same network with CoMapeo open and/or on the same project
<img width="214" alt="Screen Shot 2024-08-13 at 8 01 44 PM" src="https://github.com/user-attachments/assets/b02826fb-9684-4a74-9d2f-e1ed34056192">

- [ ] Update the sync button to 'Start Sync'
- [ ] Display _0 Devices found_ since no other devices are on the same network
- [ ] Display _No devices available to sync_ since no other devices are on the same network

## Screen 2 - Devices are on the project, same network and are on CoMapeo
<img width="206" alt="Screen Shot 2024-08-13 at 8 02 13 PM" src="https://github.com/user-attachments/assets/91f68f13-5e93-438b-8d17-8d0ea19658f2">

- [ ] Display _X Devices found_ since other devices are on the same network 
- [ ] Display _X devices available to sync_ since other devices are on the same network (the same amount as in _Devices found_)

**Design**
https://www.figma.com/design/uzynHXR0xgJu19lsCoJyXN/%F0%9F%90%9A-Shell-App?node-id=2596-796
