### ISSUE TITLE
Sync update / Waiting - no other devices Sync

### ISSUE THREAD

**Issue by ximenabb** [digidem/comapeo-mobile#603]
**Description**
- User tapped 'Start Sync' but there are no other devices syncing. User is waiting for other devices to join by clicking 'Start Sync"
- User can see there are devices found

Details : https://www.notion.so/digidem/QA-Sync-bug-3-devices-no-synced-progress-3de5f1760e934b12b673bb49b62572ec

Relates to https://github.com/digidem/comapeo-mobile/issues/602 https://github.com/digidem/comapeo-mobile/issues/604 https://github.com/digidem/comapeo-mobile/issues/605

**Todo**
<img width="199" alt="Screen Shot 2024-08-13 at 8 08 40 PM" src="https://github.com/user-attachments/assets/5af0af38-1123-49ea-8446-1a98eb9b043d">

- [ ] Display progress bar as designed 
- [ ] Add _Waiting_ on top of progress bar
- [ ] Add 'Stop' button, clicking on stop removes the device from the syncing party, if device remained on then app it can still be considered a found device
- [ ] If clicked on 'Stop', user goes back to **Screen 1** https://github.com/digidem/comapeo-mobile/issues/602

**Design**
https://www.figma.com/design/uzynHXR0xgJu19lsCoJyXN/%F0%9F%90%9A-Shell-App?node-id=2596-796
