### ISSUE TITLE
Sync update / Progress

### ISSUE THREAD

**Issue by ximenabb** [digidem/comapeo-mobile#604]
**Description**
- User has tapped on 'Start Sync' and can see various states of progress depending on how many devices are found and/or have clicked on sync
- Clicking the back button does not remove the device from the sync party, only click Stop (or closing the app/disconneting from network) will remove device from sync party

Details : https://www.notion.so/digidem/QA-Sync-bug-3-devices-no-synced-progress-3de5f1760e934b12b673bb49b62572ec

Relates to https://github.com/digidem/comapeo-mobile/issues/602 https://github.com/digidem/comapeo-mobile/issues/603 https://github.com/digidem/comapeo-mobile/issues/605

**Todo**
 ## Screen 1 - Syncing - Number of syncing devices different from devices found
<img width="197" alt="Screen Shot 2024-08-13 at 8 19 17 PM" src="https://github.com/user-attachments/assets/cfa0c570-535d-45df-9f28-94882d732eb8">

- [ ] Display _6 Devices found_ since 6 devices, other than yours, is on the same project/network
- [ ] Display _Syncing with  3 out of 6 devices_ if the device has clicked on Start Sync and 3 other devices have also done the same
- [ ] Display progress bar as designed 
- [ ] Add _Syncing_ on top of progress bar
- [ ] Add percentage of syncing under the progress bar
- [ ] If clicked on 'Stop', user goes back to **Screen 2** https://github.com/digidem/comapeo-mobile/issues/602

 ## Screen 2 - Syncing - Syncing complete but other devices are found (Partial completion state)
<img width="194" alt="Screen Shot 2024-08-13 at 8 19 33 PM" src="https://github.com/user-attachments/assets/1a3a2b07-53c1-44e2-8bb7-c80dac05ead5">

- [ ] Display _6 Devices found_ since 6 devices, other than yours, is on the same project/network
- [ ] Display _Complete! Waiting for 3 other devices_  once all devices have synced
- [ ] Display progress bar as designed 
- [ ] Add _3 out of 6 devices..._ on top of progress bar if 3/6 have indeed synced
- [ ] Add 100% percentage under the progress bar
- [ ] If clicked on 'Stop', user goes back to **Screen 2** displaying 3 available devices https://github.com/digidem/comapeo-mobile/issues/602
- [ ] If not clicked 'Stop' user can remain on that page or navigate CoMapeo and still be in the sync party
- [ ] If new device has opted to sync, see **Screen 3**

 ## Screen 3 - Syncing - Partial completion state/ Another device has joined sync party
User was on Screen 2 and a new device has joined sync party 
<img width="203" alt="Screen Shot 2024-08-13 at 8 19 50 PM" src="https://github.com/user-attachments/assets/d43de9a8-cf59-452b-99f5-5a2b18c6f416">

- [ ] Display _6 Devices found_ since 6 devices, other than yours, is on the same project/network
- [ ] Display _Syncing with  4 out of 6 devices_  since out of the 6 devices found, a 4th has opted to sync
- [ ] Display progress bar as designed - the progress bar has reset (as in not starting from scratch, but reset with the updated syncing devices)
- [ ] Add _Syncing_ on top of progress bar
- [ ] If clicked on 'Stop', user goes back to **Screen 2** displaying 4 available devices https://github.com/digidem/comapeo-mobile/issues/602

 ## Screen 4 - Another devices leaves sync party and network mid-sync
<img width="194" alt="Screen Shot 2024-08-13 at 8 20 07 PM" src="https://github.com/user-attachments/assets/1da19366-8f0f-4ec7-8eca-3c47efb8ee30">

- [ ] Display _5 Devices found_ since a device was removed from the network/closed app 
- [ ] Display _Syncing with  3 out of 5 devices_ since a device was removed from the sync party
- [ ] Display progress bar as designed - 
- [ ] If clicked on 'Stop', user goes back to **Screen 2** displaying 5 available devices https://github.com/digidem/comapeo-mobile/issues/602

**Design**
https://www.figma.com/design/uzynHXR0xgJu19lsCoJyXN/%F0%9F%90%9A-Shell-App?node-id=2596-796
