### ISSUE TITLE
Sync update / Complete

### ISSUE THREAD

**Issue by ximenabb** [digidem/comapeo-mobile#605]
**Description**
 Device has sync all its data with the found devices. 2 possible states of complete

Details : https://www.notion.so/digidem/QA-Sync-bug-3-devices-no-synced-progress-3de5f1760e934b12b673bb49b62572ec

Relates to https://github.com/digidem/comapeo-mobile/issues/603 https://github.com/digidem/comapeo-mobile/issues/604 https://github.com/digidem/comapeo-mobile/issues/602

**Todo**
## Screen 1 - Fully complete sync / device still in sync party
If device navigates to a different screen after this state, after 30 secs sync party closes. This is true ONLY when you reach this state. This is NOT true for when you actively syncing and navigate away.
<img width="196" alt="Screen Shot 2024-08-13 at 8 22 30 PM" src="https://github.com/user-attachments/assets/c72b61ed-d8ba-4701-9a1c-f191d748f189">

- [ ] Display _6 Devices found_ since 6 devices, other than yours, are on the same project/network
- [ ] Display _Complete!  You’re up to date. All data synced_ if all devices have synced
- [ ] Display progress bar as designed (green)
- [ ] Add _6 out of 6 devices_ on top of progress bar, if 6 devices synced
- [ ] Add 100% percentage of syncing under the progress bar
- [ ] If clicked on 'Stop', user goes to Screen 2 - see below

## Screen 2 - Fully complete sync / device out of sync party
<img width="194" alt="Screen Shot 2024-08-13 at 8 22 48 PM" src="https://github.com/user-attachments/assets/3f4671a5-64ae-4e32-b341-dcdff0d48e5a">

- [ ] Display _6 Devices found_ since 6 devices, other than yours, are on the same project/network
- [ ] Display _Complete!  You’re up to date. All data synced_ if all devices have synced
- [ ] Display progress bar as designed (green)
- [ ] Add _6 out of 6 devices_ on top of progress bar, if 6 devices synced
- [ ] Add 100% percentage of syncing under the progress bar
- [ ] Update 'Stop' button to _You’re all caught up!_

**Design**
https://www.figma.com/design/uzynHXR0xgJu19lsCoJyXN/%F0%9F%90%9A-Shell-App?node-id=2596-796
