### ISSUE TITLE
Coordinator / Adding Server errors

### ISSUE THREAD

**Issue by ximenabb** [digidem/comapeo-mobile#625]
**Description**
Coordinator has clicked on **Add Server** and see below possible errors if the server is not responding or in use.
Use this template for other possible errors

**Todo**

## Screen 1 - Adding url - error

<img width="281" alt="Screen Shot 2024-09-18 at 12 34 46 PM" src="https://github.com/user-attachments/assets/2d7c169d-2b5f-46aa-939f-0eb59fc81d16">

- [ ] Use usual design patterns when URL incorrect

## Screen 2 - Adding a url - Device offline
<img width="277" alt="Screen Shot 2024-09-18 at 12 35 59 PM" src="https://github.com/user-attachments/assets/d871d7d2-5ef8-4f38-aa85-60e07dc9eb39">

- [ ] Display screen as designed
- [ ] Use copy _No Internet Access_
- [ ] Use copy _Your device is offline. Connect to the Internet to add a server_
- [ ] Add a  **Go Back**  button

## Screen 3 - Unable to connect

<img width="293" alt="Screen Shot 2024-09-18 at 12 38 28 PM" src="https://github.com/user-attachments/assets/2acb84f2-3c68-4b43-9b51-475e259e7277">

- [ ] Display screen as designed
- [ ] Use copy _Unable to connect  to Server_
- [ ] _The server may not be configured correctly or there might be another issue._ 
- [ ] _Go back and try again._ 
- [ ] Add a  **Go Back**  button

## Screen 4 - Server already in use
<img width="283" alt="Screen Shot 2024-09-18 at 12 39 25 PM" src="https://github.com/user-attachments/assets/a4d62ec6-2086-4f95-bcd8-1b1f57dbdb27">

- [ ] Display screen as designed
- [ ] Use copy _Server already in use_
- [ ] _Go back to add a different server. _ 
- [ ] Add a  **Go Back**  button

**Design**
https://www.figma.com/design/iUeC0Qzhb4H0unuPfxQAsM/(Mobile)-CoMapeo?node-id=2909-1931&t=3MJwxcx0iGMHqAbR-1

**Comment by ximenabb** [comment]
Updated figma link
