### ISSUE TITLE
Leave Project /  Add Button + Screen

### ISSUE THREAD

**Issue by ximenabb** [digidem/comapeo-mobile#660]
![Image](https://github.com/user-attachments/assets/f679b953-8c76-493c-bd65-7a01bfff085b)

Notion : https://www.notion.so/digidem/Leave-Project-Add-Button-Screen-dde511446cf5408b8885977dc3e22b0a

**Todo**

## Your team
- [ ] Add **Leave Project** button next to the users device

## How to leave project - If Leave Project button is clicked

- [ ] Integrate screen as designed
- [ ] Add copy _How to Leave Project_
- [ ] _To leave this project please uninstall and reinstall Mapeo.  All project data will be removed from this device._
- [ ] If you are the only Coordinator on the project no one else will be able to edit project details or invite other devices!_
- [ ] Add **Go Back** button
- [ ] If go back button click, take user to Your Team
