### ISSUE TITLE
Add logic for media management

### ISSUE THREAD

**Issue by cimigree** [digidem/comapeo-mobile#879]
## Description
The Media Management toggle currently exists, but...
The logic needs to be added to make the toggle actually do something.
It currently exists, but is behind a feature flag.

### Todos:

- [ ] Add a hook file to house the queries to the backend related to setting and getting the media management settings
```
await mapeoApi.getIsArchiveDevice()
await mapeoApi.setIsArchiveDevice(true)
```

- [ ] Use that logic instead of the localstorage logic that is already in there `const {setMediaSyncSetting} = usePersistedSettingsAction();`
- [ ] Remove the logic related to usePersistedSettings && setMediaSyncSetting that is no longer needed
- [ ] Remove feature flag EXPO_PUBLIC_FEATURE_MEDIA_MANAGER=true
